<a href="https://colab.research.google.com/github/parjanyahk/hackaithon-project/blob/main/PlacementsProjectModel1V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [ ]:
data=pd.read_csv("/content/drive/My Drive/Placements Project Files/Model1.csv")


In [ ]:
data

Job Status  1st sem  ...  Technical Blogs  Soft skills and Communication
0             1     7.00  ...                0                              7
1             1     9.33  ...                1                             10
2             1     7.90  ...                1                              7
3             1     8.25  ...                0                              8
4             1     7.50  ...                0                              8
..          ...      ...  ...              ...                            ...
101           0     7.50  ...                0                              7
102           1     8.76  ...                1                              8
103           0     4.83  ...                0                              6
104           0     6.80  ...                0                              6
105           0     8.42  ...                1                              8

[106 rows x 55 columns]

In [ ]:
data.head()

Job Status  1st sem  ...  Technical Blogs  Soft skills and Communication
0           1     7.00  ...                0                              7
1           1     9.33  ...                1                             10
2           1     7.90  ...                1                              7
3           1     8.25  ...                0                              8
4           1     7.50  ...                0                              8

[5 rows x 55 columns]

In [ ]:
data.iloc[:53,1:].values

array([[ 7.  ,  7.  ,  6.8 , ...,  1.  ,  0.  ,  7.  ],
       [ 9.33,  8.5 ,  8.07, ...,  1.  ,  1.  , 10.  ],
       [ 7.9 ,  8.1 ,  7.43, ...,  1.  ,  1.  ,  7.  ],
       ...,
       [ 4.83,  4.75,  4.29, ...,  0.  ,  0.  ,  6.  ],
       [ 6.8 ,  6.8 ,  6.48, ...,  1.  ,  0.  ,  6.  ],
       [ 8.42,  8.67,  7.7 , ...,  1.  ,  1.  ,  8.  ]])

In [ ]:
X = preprocessing.scale(data.iloc[:53,1:].values)

In [ ]:
X

array([[-0.8793117 , -0.81897552, -0.6332845 , ...,  0.54100178,
        -0.84242354, -0.81009259],
       [ 1.2230349 ,  0.51194341,  0.4750457 , ...,  0.54100178,
         1.18705135,  2.25668649],
       [-0.06724649,  0.15703169, -0.0834829 , ...,  0.54100178,
         1.18705135, -0.81009259],
       ...,
       [-2.83729116, -2.81535392, -2.82376387, ..., -1.84842275,
        -0.84242354, -1.83235228],
       [-1.05977064, -0.99643138, -0.9125488 , ...,  0.54100178,
        -0.84242354, -1.83235228],
       [ 0.40194674,  0.66278089,  0.15214635, ...,  0.54100178,
         1.18705135,  0.21216711]])

In [ ]:
data.iloc[:53,:1].values

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0]])

In [ ]:
y = to_categorical(data.iloc[:53,:1].values)

In [ ]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [ ]:
#model
model = Sequential()
model.add(Dense(10, input_dim=54, activation='relu'))
model.add(Dense(2, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, batch_size=10)

Epoch 1/50
5/5 [==============================] - 0s 33ms/step - loss: 0.8784 - accuracy: 0.3810 - val_loss: 0.5908 - val_accuracy: 0.5455
Epoch 2/50
5/5 [==============================] - 0s 5ms/step - loss: 0.7862 - accuracy: 0.4286 - val_loss: 0.5720 - val_accuracy: 0.6364
Epoch 3/50
5/5 [==============================] - 0s 5ms/step - loss: 0.7306 - accuracy: 0.4762 - val_loss: 0.5553 - val_accuracy: 0.7273
Epoch 4/50
5/5 [==============================] - 0s 5ms/step - loss: 0.6685 - accuracy: 0.5476 - val_loss: 0.5414 - val_accuracy: 0.6364
Epoch 5/50
5/5 [==============================] - 0s 5ms/step - loss: 0.6200 - accuracy: 0.6190 - val_loss: 0.5298 - val_accuracy: 0.6364
Epoch 6/50
5/5 [==============================] - 0s 5ms/step - loss: 0.5783 - accuracy: 0.6667 - val_loss: 0.5207 - val_accuracy: 0.6364
Epoch 7/50
5/5 [==============================] - 0s 5ms/step - loss: 0.5461 - accuracy: 0.7143 - val_loss: 0.5109 - val_accuracy: 0.6364
Epoch 8/50
5/5 [=================